### ISSUE TITLE
Help on F420v3, could you please share the openwrt image for F420v3

### ISSUE THREAD

**Issue by puppywang** [msdos03/openwrt-f660#3]
Hi, thanks for your effort on porting openwrt to ZTE devices, I've got a F420v3 years ago, and I've see your note that F420v3 share the same artchteture as F660v3, so could you please share the link of openwrt image for F420v3 or provide the build guide, thanks.

**Comment by msdos03** [comment]
I have made a version for f420 v3 long time ago. But f420 v3 doesn't have USB or WIFI chip. So after flashing openwrt, it can only become a wire router with 4 ethernet ports. I gave up it a long time ago. If you still want to flash your f420 v3, I can add a target for you sometime. 

f420 v3 stock uboot can't boot custom firmware automaticly, just like the other two devices. So custom uboot is necessary. A good news is I have f420 v3 too and I think f660 v3's custom uboot will work with no problem on f420 v3.

**Comment by puppywang** [comment]
Thanks for your reply, the F420v3 is quite old and I am unable to use it as EPON modern because it failed to save the vlan when rebooted, so I am planing to do something with it, but as the image is not ready and will cost your time, I think I can just give it up. Thanks anyway.

**Comment by msdos03** [comment]
That's all right, I have F420 too so I added the target now. I've tested that my F660 uboot can run on F420. My uboot has releases, but I can't provide openwrt releases because you may need other packages. Clone it and find Marvell Avanta platform and f420-f620 target to compile! Use tftp, nand read and nand write commands in uboot to flash uboot, openwrt. Then you would be able to upgrade firmware in LuCI. There is a partition table for flashing. 
 note: kernel and ubi partition is combined in factory firmware.
	partition@0 {
		label = "u-boot";
		reg = <0 0x100000>;
	};

	partition@100000 {
		label = "kernel";
		reg = <0x100000 0x300000>;
	};

	partition@400000 {
		label = "ubi";
		reg = <0x400000 0x1c00000>;
	};

**Comment by puppywang** [comment]
Very appreciated. I am trying to compile the repo now.
